from __future__ import annotations

from collections import defaultdict

from bdf2rad.core.plugin_helpers import (
    rb,
    emit,
)


def _fmt10(value: int) -> str:
    return f"{int(value):>10d}"


def _brick_row(
    eid: int,
    nodes: list[int],
) -> str:
    """
    Official conversion path:

        Nastran CHEXA20
              ->
        first-order element
              ->
        Radioss /BRICK

    /BRICK requires exactly:
        brick_ID + 8 node IDs
    """

    if len(nodes) != 20:
        raise ValueError(
            f"CHEXA20 element {eid} requires exactly "
            f"20 source nodes, got {len(nodes)}"
        )

    # ------------------------------------------------------------
    # Official downgrade:
    #
    # CHEXA20:
    #   node 1..8  = corner nodes
    #   node 9..20 = midside nodes
    #
    # /BRICK:
    #   only 8 nodes
    #
    # Therefore keep only the first 8 corner nodes.
    # ------------------------------------------------------------
    corner_nodes = nodes[:8]

    return (
        _fmt10(eid)
        + "".join(
            _fmt10(node_id)
            for node_id in corner_nodes
        )
    )


def translate(
    model,
    ctx,
    plugin,
):
    """
    Translate Nastran CHEXA20 to OpenRadioss /BRICK
    following the official Nastran-to-Radioss conversion mapping.

    Source:
        CHEXA with 20 nodes

    Target:
        /BRICK/<part_ID>

    Conversion:
        20-node source -> first-order 8-node target

    No BRIC20 output is generated by this translator.
    """

    groups = defaultdict(list)

    # ------------------------------------------------------------
    # Select only true CHEXA20 elements.
    # CHEXA8 is handled by the separate CHEXA8 plugin.
    # ------------------------------------------------------------
    for element in model.elements.values():

        if (
            element.typ == "CHEXA"
            and len(element.nodes) == 20
        ):
            groups[
                element.pid
            ].append(
                element
            )

    blocks = []
    audit = []

    for pid, elements in sorted(
        groups.items()
    ):

        # --------------------------------------------------------
        # PART translator creates a family-specific map.
        #
        # The official target family for CHEXA20 is BRICK.
        # --------------------------------------------------------
        part = (
            ctx.metadata
            .get(
                "part_map",
                {},
            )
            .get(
                (
                    pid,
                    "BRICK",
                ),
                pid,
            )
        )

        rows = []

        for element in sorted(
            elements,
            key=lambda item: item.eid,
        ):

            # Validate all 20 source node IDs exist.
            missing = [
                node_id
                for node_id in element.nodes
                if node_id not in model.nodes
            ]

            if missing:
                preview = ", ".join(
                    str(node_id)
                    for node_id in missing[:20]
                )

                raise ValueError(
                    f"CHEXA20 element {element.eid} "
                    f"references undefined node(s): "
                    f"{preview}"
                )

            # ----------------------------------------------------
            # First-order downgrade:
            # keep only corner nodes 1..8.
            # ----------------------------------------------------
            rows.append(
                _brick_row(
                    element.eid,
                    element.nodes,
                )
            )

        rendered = emit(
            plugin,
            {
                "PART": part,
                "ROWS": "\n".join(rows),
            },
        )

        blocks.append(
            rb(
                plugin,
                f"/BRICK/{part}",
                rendered,
            )
        )

        audit.append(
            {
                "card": "CHEXA",
                "source_order": 20,
                "status": "translated_first_order",
                "target": f"/BRICK/{part}",
                "count": len(elements),
                "source_pid": pid,
                "source_nodes_per_element": 20,
                "target_nodes_per_element": 8,
                "source_nodes_preserved": {
                    "corner_nodes": 8,
                    "midside_nodes": 12,
                    "midside_nodes_used": False,
                },
                "mapping_basis": (
                    "Nastran CHEXA20 -> "
                    "first-order -> /BRICK"
                ),
            }
        )

    return (
        blocks,
        audit,
    )